import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <ul>
        <h1>Jamboree</h1>
        <li><a class="special-button"href="#">Open Chatroom</a></li>
        <li><a href="#">Contact</a></li>

        <li><a href="#">Features</a></li>

      </ul>

      <div class="hero">
        <div class="sub-hero">
        <h1>One time, never again</h1>
        <h2> Say what's on your mind</h2>
          <br></br>
        <a>Start Chatting</a>
          </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright © 2022 Jamboree, All Rights Reserved

        </a>
      </footer>
    </div>
  )
}
